version: '2'
services:
  zookeeper:
    extends:
      file: ./common-services.yaml
      service: zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPICFIRST_BOOTSTRAPADDRESS: kafka
    networks:
      - backend-stack-demo-network

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - backend-stack-demo-network

  backend-stack-demo:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    image: leocr/backend-stack-demo:latest
    ports:
      - 8080:8080
    volumes:
      - backend-stack-demo-volume:/tmp/backend-stack-demo-volume
    networks:
      - backend-stack-demo-network
    logging:
      driver: json-file
    depends_on:
      - kafka

networks:
  backend-stack-demo-network:
    driver: bridge

volumes:
  backend-stack-demo-volume:
    external: false