version: '2.1'
services:
  zookeeper:
    extends:
      file: ./common-services.yaml
      service: zookeeper

  kafka:
    extends:
      file: ./common-services.yaml
      service: kafka
    depends_on:
      - zookeeper

  kafdrop:
    extends:
      file: ./common-services.yaml
      service: kafdrop
    depends_on:
      - kafka

  redis:
    extends:
      file: ./common-services.yaml
      service: redis

  rabbit:
    extends:
      file: ./common-services.yaml
      service: rabbit

  mongo:
    extends:
      file: ./common-services.yaml
      service: mongo

  backend-stack-demo:
    extends:
      file: ./common-services.yaml
      service: backend-stack-demo
    depends_on:
      - kafka
      - redis
      - rabbit
      - mongo

networks:
  backend-stack-demo-network:
    driver: bridge

volumes:
  backend-stack-demo-volume:
    external: false
